import io
from docx import Document
from weasyprint import HTML
from markdown import markdown
import os

def summary_to_word(summary: str) -> io.BytesIO:
    doc = Document()
    for line in summary.splitlines():
        if line.startswith("##"):
            doc.add_heading(line.replace("##", "").strip(), level=1)
        elif line.startswith("###"):
            doc.add_heading(line.replace("###", "").strip(), level=2)
        else:
            doc.add_paragraph(line)
    doc.add_paragraph("\n---\nAI-generated summary. Not legal advice.")
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

def summary_to_pdf(summary: str) -> io.BytesIO:
    html = f"<html><body><pre>{summary}</pre><hr><em>AI-generated summary. Not legal advice.</em></body></html>"
    buffer = io.BytesIO(HTML(string=html).write_pdf())
    buffer.seek(0)
    return buffer

def summary_to_html(summary: str, output_path: str = "docs/summary.html"):
    # Convert markdown text to proper HTML
    html_summary = markdown(summary, extensions=["extra", "sane_lists"])

    html_template = f"""
    <html>
    <head>
        <meta charset="utf-8">
        <title>Tenancy Agreement Summary</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                line-height: 1.6;
            }}
            h1, h2, h3 {{ color: #2C3E50; }}
            .risk {{ color: red; font-weight: bold; }}
            code {{ background: #eee; padding: 2px 4px; }}
            pre {{ background: #f4f4f4; padding: 10px; overflow-x: auto; }}
        </style>
    </head>
    <body>
        <h1>🏡 NSW Tenancy Agreement Summary</h1>
        {html_summary}
        <hr>
        <p><small>⚠️ This summary is generated by AI. For legal advice, contact NSW Fair Trading.</small></p>
    </body>
    </html>
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_template)
    return output_path